name: Translate README

on:
  workflow_run:
    workflows: ["Xiangqi Move Handler"]
    types:
      - completed

permissions:
  contents: write

jobs:
  translate:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Translate to English
        uses: dephraiim/translate-readme@main
        with:
          LANG: en
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.en.md
          git commit -m ":memo: Auto translate README" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
