```yaml
name: Xiangqi Move Handler

on:
  issues:
    types: [opened]

jobs:
  handle-move:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'xiangqi|move|')
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install requirements
        run: pip install -r scripts/requirements.txt || true

      - name: Run move script
        run: python scripts/xiangqi.py
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md data/board.json
          git commit -m "update board" || echo "No changes to commit"
          git push